### ISSUE TITLE
UInt64 downcast from JSON fails on Linux

### ISSUE THREAD

**Issue by twostraws** [IBM-Swift/Kitura-CredentialsGitHub#27]
When authenticating using GitHub, this line of code fails when run using Swift 3.1.1 on Linux: https://github.com/IBM-Swift/Kitura-CredentialsGitHub/blob/daac5a9ed9b5aff0d79a62588e4c59d3c32f2d5b/Sources/CredentialsGitHub/CredentialsGitHub.swift#L221

It works fine on macOS/Swift 4.0 as-is, but changing to `as? Int` appears to clear the problem on Linux while still working on macOS.

**Comment by youming-lin** [comment]
@twostraws I've merged fix and tagged 1.7.1
